spring:
  thymeleaf:
    mode: HTML
  profiles:
    active: pro
  mvc:
    throw-exception-if-no-handler-found: true #出现错误时，直接抛出异常
    static-path-pattern: /static/**
  mail:
    host: smtp.163.com
    username: li05012@163.com
    password: QMBAHBTFWNLKUMMD
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
jwt:
  secret: YJVDIp64Xr2AHPbnVCiO #JWT加解密使用的**
  expiration: 604800 #JWT的超期限时间(60*60*24*7)